- name: Install mariadb
  apt: name=mariadb-server state=latest

- name: Install php-mysql
  apt: name=php-mysql state=latest

- name: Install python-mysqldb
  apt: name=python-mysqldb state=latest

- name: Create database
  mysql_db: name={{ db_name }} state=present

- name: Create database user
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL"
    host: 'localhost'
    state: present