# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bskton/web"

  config.vm.network "private_network", ip: "192.168.34.10"
  config.vm.network "forwarded_port", guest: 8000, host: 8000
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.network "forwarded_port", guest: 3001, host: 3001

  config.vm.provider "virtualbox" do |vb|
    vb.name = "scatar"
    vb.memory = "512"
  end

  config.vm.provision :shell, path: "bootstrap.sh"
end